---
title: "Team; Lab 4"
author: "Evan Mills, Max Farver"
date: "March 26, 2019"
output: html_document
---

```{r}
library(tidyr)
library(readxl)
library(dplyr)
defense <- read_excel('cyclonesFootball2018.xlsx', sheet='Defensive')
str(defense)
```

```{r}
offense <- read_excel('cyclonesFootball2018.xlsx', sheet='Offensive')
str(offense)
```

```{r}
bio <- read_excel('cyclonesFootball2018.xlsx', sheet='Biography')
str(bio)
```

```{r}
offClean <- offense

offClean <- offClean %>% mutate(Receiving_REC = as.numeric(Receiving_REC))

offClean <- offClean %>% mutate(Receiving_YDS = as.numeric(Receiving_YDS))

offClean <- offClean %>% mutate(Receiving_TD = as.numeric(Receiving_TD))

offClean <- offClean %>% mutate(Rushing_ATT = as.numeric(Rushing_ATT))

offClean <- offClean %>% mutate(Rushing_YDS = as.numeric(Rushing_YDS))

offClean <- offClean %>% mutate(Rushing_TD = as.numeric(Rushing_TD))

offClean <- offClean %>% mutate('Passing_CMP-ATT' = as.numeric('Passing_CMP-ATT'))

offClean <- offClean %>% mutate(Passing_YDS = as.numeric(Passing_YDS))

offClean <- offClean %>% mutate(Passing_TD = as.numeric(Passing_TD))

offClean <- offClean %>% mutate(Passing_INT = as.numeric(Passing_INT))

str(offClean)
```

```{r}
defClean <- defense

defClean <- defClean %>% mutate(Tackles_Solo, Tackles_Solo = as.numeric(Tackles_Solo))

defClean <- defClean %>% mutate(Tackles_ASST, Tackles_ASST = as.numeric(Tackles_ASST))

defClean <- defClean %>% mutate(Tackles_TFL, Tackles_TFL = as.numeric(Tackles_TFL))

defClean <- defClean %>% mutate(Tackles_Sack, Tackles_Sack = as.numeric(Tackles_Sack))

defClean <- defClean %>% mutate(Turnover_FF, Turnover_FF = as.numeric(Turnover_FF))

defClean <- defClean %>% mutate(Turnover_FR, Turnover_FR = as.numeric(Turnover_FR))

defClean <- defClean %>% mutate(Turnover_INT, Turnover_INT = as.numeric(Turnover_INT))

defClean <- defClean %>% mutate(Pass_QBH, Pass_QBH = as.numeric(Pass_QBH))

defClean <- defClean %>% mutate(Pass_PB, Pass_PB = as.numeric(Pass_PB))

str(defClean)

```{r}
cleanBio <- bio %>% mutate(Weight, Weight = as.numeric(Weight))
str(cleanBio)
```